### ISSUE TITLE
StackOverflowError when parsing many unclosed tags in series

### ISSUE THREAD

**Issue by tkocmathla** [davidsantiago/hickory#50]
Hickory throws a StackOverflowError when parsing a document with a long series of unclosed HTML tags.
```
(-> (clojure.string/join "\n" (repeat 2048 "<font>abc"))
    hickory.core/parse       ; this works
    hickory.core/as-hickory) ; this also fails with as-hiccup
```
The stack trace repeats this section over and over:
```
              clojure.core/map/fn       core.clj: 2726
                hickory.core/fn/G       core.clj:   21
                  hickory.core/fn       core.clj:  106
                clojure.core/into       core.clj: 6771
              clojure.core/reduce       core.clj: 6704
      clojure.core.protocols/fn/G  protocols.clj:   13
        clojure.core.protocols/fn  protocols.clj:   75
clojure.core.protocols/seq-reduce  protocols.clj:   31
      clojure.core.protocols/fn/G  protocols.clj:   19
        clojure.core.protocols/fn  protocols.clj:  168
                clojure.core/next       core.clj:   64
```
I'm using clojure 1.9.0-alpha14 and hickory 0.7.1.

**Comment by tkocmathla** [comment]
I also tested this with clojure 1.8.0 and the problem exists there as well. The stack trace is identical except for line numbers.

**Comment by davidsantiago** [comment]
Hm, yeah, that's gonna do that. The problem is that a protocol is used to convert between different representations of the data. The element node has to first call this protocol function recursively on its children, in order to get the value to add to itself. I will think about this some more, but for right now, I don't see a way to get around this easily. 

Typically when parsing a potentially infinitely recursive thing, you could use a stack on the heap and manually manage it, instead of implicitly managing it on the actual stack frames of the functions. But with clojure's immutable data structures, it makes you need to have all the elements in a given data structure already finished before you create the thing that holds them. Maybe there is something we could do with zippers here, or maybe we'd need to go into Java and use mutability for this. I'll need to think about it more. 

Let me know if you want to work on this.

**Comment by tkocmathla** [comment]
In 135faba, I replaced the recursive protocol implementation with an iterative one using zippers as you suggested. This passes all the existing unit tests. So far, this is just for hickory, but I think I could easily do the same for hiccup. 

What do you think?

**Comment by tkocmathla** [comment]
It looks there are some other areas we'd have to convert from recursive to iterative, like hickory.render/hickory-to-html and maybe the hickory.select/select* fns.

**Comment by davidsantiago** [comment]
Yeah, no doubt. Did you see my comment on your commit?

**Comment by tkocmathla** [comment]
I did, thanks. I'll have a look at integrating back into the protocol this weekend.

**Comment by tkocmathla** [comment]
By the way, I was wrong about needing to change the hickory.select/select* fns; they're already iterative and seem to work fine with this pathological case:

```
(->> (apply str (repeat 2048 "<font>abc"))
     hickory/parse
     hickory/as-hickory
     (select/select (select/tag :font))
     count)
;;=> 2048
```

**Comment by tkocmathla** [comment]
I updated #51 with a solution that better preserves the protocol, I think (2d21efa). Let me know what you think.
